apiVersion: v1
kind: Service
metadata:
  name: finpay-admin-web-portal-service
spec:
  selector:
    app: finpay-admin-web-portal
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
